name: NorikoFoundation
favicon: null
layout_spectrum: 0.9161908018868417
typography_spectrum: 0.6944131716154516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25015435134992003
  lightness: 0.2318656099960208
  saturation: 0.7982025137171149
  rhythmicContrast: 0.3403633239213377
purpose: []
